### ISSUE TITLE
NUI window crashes and locks up buttons

### ISSUE THREAD

**Issue by sheriffcounty** [randomsean/RS9000#7]
When I open the menu in the new version, it freezes, I can’t close it, and the buttons do not work either.
(sorry my low fps and graphics)
https://youtu.be/dO8VE5y0HsQ

**Comment by randomsean** [comment]
Did you copy all the files from the folder during installation?

**Comment by sheriffcounty** [comment]
yes

**Comment by sheriffcounty** [comment]
Is the case of letters in the resource important? does he need to be exactly rs9000? Or can I have another name?

**Comment by randomsean** [comment]
It needs to be exactly "rs9000".

In the future, I can add support for renaming. However, due to the nature of the FiveM NUI API all resource names must be lower case.

**Comment by sheriffcounty** [comment]
ok, thanks
